apiVersion: v1
kind: Secret
metadata:
  name: ambar-secrets
  namespace: ambar
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://ambar:CHANGE_ME@mysql-primary.ambar.svc.cluster.local:3306/ambar
  READ_DATABASE_URL: mysql+pymysql://ambar:CHANGE_ME@mysql-replica.ambar.svc.cluster.local:3306/ambar
  REDIS_URL: redis://redis-cluster.ambar.svc.cluster.local:6379/0
  RABBITMQ_URL: amqp://ambar:CHANGE_ME@rabbitmq.ambar.svc.cluster.local:5672/
  JWT_SECRET_KEY: CHANGE_ME_64_CHAR_RANDOM
  INTERNAL_SERVICE_SECRET: CHANGE_ME_INTERNAL
  MINIO_ACCESS_KEY: CHANGE_ME
  MINIO_SECRET_KEY: CHANGE_ME
